services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TestApi
    ports:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080